### ISSUE TITLE
Regarding the wordmark

### ISSUE THREAD

**Issue by Dimpal-Kalita** [doki-theme/doki-theme-web#108]
How to change the wordmark "doki theme" present in the home page permanently?

**Comment by Unthrottled** [comment]
Are you talking about turning it off? This video starting at 0:28 shows you how to do that. When toggled it will remain off.

https://user-images.githubusercontent.com/15972415/157995434-30b5bdfc-b005-416f-a3fa-4bfdf72bc1be.mp4

Changing the words used a different story, and currently isn't implemented.

**Comment by Dimpal-Kalita** [comment]
I want to change the title
"doki theme" to something of my choice.
How can I do it?

**Comment by Unthrottled** [comment]
It's hardcoded in the source here https://github.com/doki-theme/doki-theme-web/blob/bf008fc553015015a91efa249c01fe4bc706396e/pluginSource/src/tab/components/SearchWidget.tsx#L70

If you want it now, you can always go to your `newTab` extension, locate & open the [tab.js](https://raw.githubusercontent.com/doki-theme/doki-theme-web/master/chromeThemes/Aqua's%20Extensions/newTab/js/tab.js), search for `createElement("div",{className:"wordmark"},"Doki Theme"))` and change `Doki Theme` to whatever you want. Then save & reload the newTab plugin.

If you don't want to do that, you'll have to wait until I get time to add that feature.

**Comment by Dimpal-Kalita** [comment]
Done, Thanks
