### ISSUE TITLE
Always loading the doki theme plugin?

### ISSUE THREAD

**Issue by Edx09** [doki-theme/doki-theme-web#47]
Is there any way to always load the plugin?

( I already tried the web-ext method but i accidentally deleted the cache and now it wont work any more )

**Comment by Unthrottled** [comment]
If you are talking about the FireFox plugin, yeah, I was literally just thinking about how annoying that is today for me. 

I'll work on publishing the extension to the store.

**Comment by Edx09** [comment]
Thanks !

**Comment by Unthrottled** [comment]
I just submitted the add on for review by the Mozilla Admins. Will let you know when it ready.

**Comment by Unthrottled** [comment]
@Edx09 The add-on is now publicly available to be installed! No more having to re-install after restart 🎉 

https://addons.mozilla.org/en-US/firefox/addon/doki-theme-for-firefox/
