### ISSUE TITLE
Doki Theme overwriting active tab when restoring window

### ISSUE THREAD

**Issue by kxmndz** [doki-theme/doki-theme-web#51]
**Describe the bug**
Doki Theme is replacing the latest active tab with a new tab when reopening closed Firefox windows.

**To Reproduce**
1. Open a Firefox window
2. Turn on "Restore previous session" in Settings > General > Startup
3. Open at least 1 tab
4. Close the window
5. Reopen Firefox

**Expected Behavior**
Reopening the window should restore the previous window's tabs, but Doki Theme is overwriting the active tab with the blank (new) page even if it previously had an open resource.

**Environment**
- Firefox Developer Edition 91.0b3
- Doki Theme for Firefox 11.0.1
- Windows 10 Home 21H1 64-bit (build 19043)

**Comment by Unthrottled** [comment]
Ah. I am able to reproduce the issue. 

Wonder why I haven't noticed this issue.
FireFox is my daily driver.

I'll have some time later this week to look into the issue. Thanks for providing a detailed report!

**Comment by kxmndz** [comment]
I can provide a screen recording of the bug happening if you need it, it happens every time on my device. My workaround is to open a new blank tab before closing so it doesn't replace any of the tabs I'm using.

**Comment by kxmndz** [comment]
I'm sure it's Doki because I've tried disabling everything else, and it still happens. Screen recording [here](https://user-images.githubusercontent.com/71072915/126343561-c7c3f348-eea7-40ad-81e9-e489e76d3f68.mp4).

**Comment by Unthrottled** [comment]
@kxmndz Yup, that's what happened to me as well. I was able to reproduce the issue, fairly confident it is an issue with the plugin. Thanks!

I also think I know why I didn't notice before you though.

> My workaround is to open a new blank tab before closing so it doesn't replace any of the tabs I'm using.

I always have a blank empty tab open, I always switch to it when I am done with the browser so I can look at a pretty girl 😂

**Comment by Unthrottled** [comment]
@kxmndz Aight, version v12.2.0 has been published to the marketplace and is available for update!

 I've verified the fix, I closed all my tabs for you 😭 

Thank you for taking the time to report the issue!
