### ISSUE TITLE
How do i get full browser customisation in Firefox

### ISSUE THREAD

**Issue by Texerman** [doki-theme/doki-theme-web#59]
How do I get the full Customizsation like in Chrome but just in Firefox?

**Comment by Unthrottled** [comment]
Hey! I am not quite sure what `Customization` you are talking about. What feature are is in chrome that isn't in firefox?

**Comment by Texerman** [comment]
Sorry for my unclear massage. In Chrome the Scroll bar and marked Text changes with the Theme you chose. And my question is if its possible to have that feature in Firefox and if yes how to get it.

**Comment by Unthrottled** [comment]
Ah! Okay, I am picking up what you are putting down.

> is it possible to have that feature in Firefox 

I am going to say _probably_. However, that functionality has not been build out yet. 

Not quite sure if the scroll bars can be re-styled in Firefox, but the text selection stuff should be possible. 

I've got this on my radar, but there is a lot of other things that I need to work on first, so it will probably be a while. If somebody else feels inspired, they can build out the same functionality as the `Master Extension`. 

Thanks for understanding and the interest!

**Comment by Unthrottled** [comment]
@Texerman Since the plugin is currently disabled in the marketplace, you can track the status of when it might be published by following #60
