### ISSUE TITLE
The Firefox addon link is broken

### ISSUE THREAD

**Issue by shift-eleven** [doki-theme/doki-theme-web#65]
**Is your feature request related to a problem? Please describe.**
The link to Firefox addon link is broken

**Describe the solution you'd like**
That the doki web theme is available as an addon for firefox

**Describe alternatives you've considered**
self-loading it but that only keeps it temporarily

**Comment by Unthrottled** [comment]
Yeah, this is a bit lame, you can track the issue on #60 . I'll close that issue once it is public, sorry for the inconvenience!
