### ISSUE TITLE
No theme on firefox startup

### ISSUE THREAD

**Issue by landiDev** [doki-theme/doki-theme-web#74]
**Describe the bug**
When starting firefox again the browser opens onto the doki homepage as expected but the theme is not applied until selecting your waifu again

**To Reproduce**
1. Close firefox
2. Open firefox

....yeah, thats just about it

**Expected Behavior**
You can check the Screenshots section to see the expected and actual behavior of the theme

**Environment**
OS: Windows | Browser: Firefox | Extension Version: Latest from the Marketplace (14.0.0)

**Screenshots**
![Screenshot 2021-10-07 191117](https://user-images.githubusercontent.com/40150678/136432348-a5812cb2-e976-4b87-8c5e-9fa4a393d30f.png)
This is the expected outcome of starting firefox ^
![Screenshot 2021-10-07 191304](https://user-images.githubusercontent.com/40150678/136432436-66a94abd-3fc8-4a96-80a4-db9910be8dd6.png)
This is the actual outcome ^

**Comment by Unthrottled** [comment]
Thank you for reporting this issue. I also noticed this too, there should be a fix in #72

**Comment by Unthrottled** [comment]
I can confirm that `15.0.2` fixes this issue. I had to close all my tabs tho 😭
