### ISSUE TITLE
Add option to make extension respect system theme color

### ISSUE THREAD

**Issue by beam2546** [doki-theme/doki-theme-web#82]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem. I'm using Windows Auto Dark Mode on my Windows PC and built-in auto switch on my MacBook to switch to dark mode at night and switch back to light mode during day. Normally, I set theme setting to "Auto" on Firefox so that it will auto switch to dark theme and enable Dark Reader at night when enable "Use system color scheme" option. With Doki Theme extension installed, it won't switch to dark theme by it own and Dark Reader won't activate until I switch dark mode on in Doki Theme extension.

**Describe the solution you'd like**
Something similar to Firefox's "Auto" theme where it will switching between light and dark mode according to system theme color and Discord's "Sync with computer" option where Discord theme will switch according system theme color (yes I actually use Discord light theme during day:laughing:)

**Describe alternatives you've considered**
For now, I'm switching manually which is fine but having option to do it automatically would be great!

**Comment by Unthrottled** [comment]
I like the idea, thanks for the suggestion.

Looks like somebody else figured out how to do it https://remysharp.com/2021/06/21/light-dark-firefox-theme-switching

**Comment by Unthrottled** [comment]
@beam2546 

When you in visioned using this new feature, were you expecting:

- To be able to choose what dark doki theme you wanted to use when your OS switches to dark mode and what light doki theme you wanted to use when your OS switches to light mode?
- To have the plugin randomly choose a light doki theme when the OS switches to light mode and pick a random dark doki theme when your OS switches to dark mode?
- Or something else?

**Comment by Unthrottled** [comment]
Here is a sample plugin from another product that does what the first option states

https://user-images.githubusercontent.com/15972415/146554544-4b6ad4ab-3325-433a-89d8-b213590f7069.mp4

(minus the time setting, it will respect the OS theme instead)

**Comment by beam2546** [comment]
Definitely first option. It should let you choose which theme you want to use when OS switch between light and dark mode.

**Comment by Unthrottled** [comment]
I'll let you know when v18 is published for use, just got a couple of things that need to be taken care of.

**Comment by Unthrottled** [comment]
Aight, v18.1.0 has been published to the add-on marketplace. Thanks for the feature request and your patience!
