### ISSUE TITLE
[FireFox] - Opt-In all features

### ISSUE THREAD

**Issue by Unthrottled** [doki-theme/doki-theme-web#85]
According to the add-on policies, we need all the features provided by the add-on, to be opt-in and not "on by default"

> The features must be “opt-in”, meaning the user has to take non-default action to enact the change. Changes prompted by Firefox after the add-on is installed do not require an additional opt-in. The permissions prompt shown when installing an add-on does not alleviate the need for an opt-in.

**Comment by Unthrottled** [comment]
I'll work on this.

**Comment by ZimCodes** [comment]
As mentioned in #86:
> the search permission in the manifest can be placed as an optional_permission instead of a required one.
