### ISSUE TITLE
Not working on Brave.

### ISSUE THREAD

**Issue by Alispezzate** [doki-theme/doki-theme-web#98]
When I install the theme on Brave browser the new page background doesn't change, is there any way to make it work?

**Comment by Unthrottled** [comment]
Huh, I haven't tried to install it on Brave before.

It seems to be working for me:


https://user-images.githubusercontent.com/15972415/160018947-784e4b1e-08ae-416d-96e6-530f41c8a892.mp4


My Brave Version:
`[Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)](https://brave.com/latest/)`

Did you install both extensions?

**Comment by Alispezzate** [comment]
Oh, I didn't install both extensions, now it works, thanks!

**Comment by Unthrottled** [comment]
Cool! I wish I could have just had one plugin, but you can only have an extension either be a Theme Extension or a Non-Theme extension. Which is a bit annoying.

Anyways, something I noticed is that Brave's active tab underline is a bit off. If you care, you can follow #99 and install the fix once that is closed :)
